name: Build TTF2SDK
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate protobuf project files
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: cmake -B thirdparty\protobuf_build -G "Visual Studio 16 2019" -Dprotobuf_BUILD_TESTS=OFF thirdparty\protobuf\cmake

      - name: Patch build version
        run: |
          $file = "TTF2SDK\TTF2SDK.rc"
          $find = '#define VER_GIT_HASH "dev"'
          $replace = "#define VER_GIT_HASH ""${env:GITHUB_SHA}"""
          (Get-Content $file).replace($find, $replace) | Set-Content $file
        shell: powershell

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release TTF2SDK.sln

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ttf2sdk-dll
          path: |
            x64/Release/TTF2SDK.dll
            x64/Release/TTF2SDK.pdb

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            x64/Release/TTF2SDK.dll
            x64/Release/TTF2SDK.pdb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
